export const CHANGE_IS_SHOW_ALL = 'CHANGE_IS_SHOW_ALL';
export const DELETE_ALL_TODOS = 'DELETE_ALL_TODOS';
export const DELETE_TODO = 'DELETE_TODO';
export const ARCHIVE_TODO = 'ARCHIVE_TODO';

export const DELETE_STATISTICS = 'DELETE_STATISTICS';
export const CHANGE_STATISTICS = 'CHANGE_STATISTICS';
export const SET_CURRENT_TODO_NUM = 'SET_CURRENT_TODO_NUM';
export const SET_CURRENT_TODO = 'SET_CURRENT_TODO';
export const CLEAN_CURRENT_TODO = 'CLEAN_CURRENT_TODO';
export const REMOVE_CURRENT_TODO = 'REMOVE_CURRENT_TODO';
export const ADD_NEW_TODO = 'ADD_NEW_TODO';
export const CHANGE_CURRENT_CATEGORY_ID = 'CHANGE_CURRENT_CATEGORY_ID';
export const CHANGE_CURRENT_NAME = 'CHANGE_CURRENT_NAME';
export const CHANGE_CURRENT_CONTENT = 'CHANGE_CURRENT_CONTENT';

