export const CHANGE_IS_SHOW_ALL = 'CHANGE_IS_SHOW_ALL';
export const DELETE_ALL_TODOS = 'DELETE_ALL_TODOS';
export const DELETE_TODO = 'DELETE_TODO';
export const ARCHIVE_TODO = 'ARCHIVE_TODO';

export const DELETE_STATISTICS = 'DELETE_STATISTICS';
export const CHANGE_STATISTICS = 'CHANGE_STATISTICS';
export const SET_CURRENT_TODO = 'SET_CURRENT_TODO';
export const REMOVE_CURRENT_TODO = 'REMOVE_CURRENT_TODO';


